version: "3.7"
x-buildargs: &buildargs
    SERVER_VERSION: ${SERVER_VERSION}
    BUILD_METHOD: ${BUILD_METHOD}

services:
    baseimage:
        build:
            context: seafile
            target: ${BUILD_METHOD}
            args: *buildargs
        image: jojo243/seafile-base:${SERVER_VERSION}
        container_name: seafile_base
        env_file: .env

    seafile:
        restart: always
        build:
            context: seafile
            target: prod
            args: *buildargs
        image: jojo243/seafile:${SERVER_VERSION}
        container_name: seafile_seafile
        volumes:
            - ./seafile/haiwen:/haiwen/
            - ./seafile/seafile/:/data/
        depends_on:
            - db
        env_file: .env
        environment:
            LC_ALL: C

    nginx:
        restart: always
        image: arm64v8/nginx:alpine
        container_name: seafile_nginx
        volumes:
            - ./nginx/init/:/init/
            - ./nginx/conf/:/opt/conf/
            - ./seafile/haiwen/:/opt/seafile/
            - ./ssl:/opt/ssl:ro
        entrypoint: /init/init.sh
        command: ["nginx", "-g", "daemon off;"]
        ports:
            - ${PORT}:${PORT}
        env_file: .env
        depends_on:
            - seafile
    db:
        restart: always
        build:
            context: db
            args:
              - MYSQL_VERSION=${MYSQL_VERSION}
        image: jojo243/mysql:${MYSQL_VERSION}
        container_name: seafile_db
        volumes:
            - ./db/data:/db
        env_file: .env
