version: '2'
services:
    baseimage:
        build:
            context: build
            args:
              - "SERVER_VERSION=${SERVER_VERSION}"
        image: jojo243/seafile-base:${SERVER_VERSION}
        container_name: seafile_base
        volumes:
            - ./build/src:/haiwen
    seafile:
        build:
            context: seafile
        restart: always
        image: jojo243/seafile:${SERVER_VERSION}
        container_name: seafile_seafile
        volumes:
            - ./build/src/:/usr/src/
            - ./seafile/haiwen:/haiwen/
            - ./seafile/seafile/:/data/
        depends_on:
            - db
        env_file: .env
        environment:
            - "LC_ALL=C"

    nginx:
        restart: always
        image: arm64v8/nginx
        container_name: seafile_nginx
        volumes:
            - ./nginx/init/:/init/
            - ./nginx/conf/:/opt/conf/
            - ./seafile/haiwen/:/opt/seafile/
            - ./ssl:/opt/ssl:ro
        entrypoint: /init/init.sh
        command: ["nginx", "-g", "daemon off;"]
        ports:
            - ${PORT}:8080
        env_file: .env
        depends_on:
            - seafile
    db:
        build:
            context: db
        restart: always
        image: jojo243/mysql
        container_name: seafile_db
        volumes:
            - ./db/data:/var/lib/mysql
        env_file: .env
